#! /bin/sh

sxhkd &

# Cursor for the root window
xsetroot -cursor_name left_ptr

bspc monitor -d web term chat code music 6 7 8

bspc config border_width         3 
bspc config window_gap           3

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop ^1 -l monocle

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^1
bspc rule -a vivaldi desktop=^1
bspc rule -a Code desktop=^4
bspc rule -a Genymotion desktop=^3
bspc rule -a TelegramDesktop desktop=^3
bspc rule -a Quassel IRC desktop=^3
bspc rule -a Subl desktop=^4
bspc rule -a Spotify desktop=^5
bspc rule -a Eog state=floating
bspc rule -a Dolphin state=floating
bspc rule -a File-roller state=floating
bspc rule -a gscreenshot state=floating

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
#bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa

picom --config ~/.config/picom.conf -b
xrdb -merge ~/.Xdefaults

# Configure wallpaper
feh --bg-scale --no-fehbg ~/wallpaper.jpg

# Start dunst notification service
dunst &

# Screen locker
#  - lock screen after 2 minutes
xset 30
xss-lock xsecurelock -n

# Start polybar
bash ~/.config/polybar/launch.sh
